version: '3'
services:
  GPU:
    image: cavelab:latest-gpu
    build:
      context: .
      dockerfile: ./bin/dockerfile/GPU
    ports:
     - "5000:5000"
    environment:
    - BUILD_ENV=Docker
    volumes:
     - ../:/projects
     - .:/cavelab
    stdin_open: true
    tty: true
